<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Datezy.Domain\Datezy.Domain.csproj" />
    <ProjectReference Include="..\Datezy.Contracts\Datezy.Contracts.csproj" />
    <ProjectReference Include="..\Datezy.Shared\Datezy.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
